# Download list:
numpy, matplotlib, pillow, pandas, scikit-learn

1. [Download CUDA and cuDNN](https://docs.nvidia.com/deeplearning/cudnn/support-matrix/index.html)

2. After download the cuDNN:

>copy the *\bin\cudnn64_8.dll to C:\Program Files\NvIDIA GPU Computing Tollkit\CUDA\v11.X\bin

>copy the *\include\cudnn.h to C:\Program Files\NvIDIA GPU Computing Tollkit\CUDA\v11.X\include

>copy the *\lib\x64\cudnn.lib to C:\Program Files\NvIDIA GPU Computing Tollkit\CUDA\v11.X\lib\x64

3. [Select your preferences and run the install command](https://pytorch.org/get-started/locally/)

In [1]:
# check torch version
import torch
print(torch.__version__)

2.0.0


In [2]:
#check cuda was installed or not
USE_CUDA = torch.cuda.is_available()
device = torch.device("cuda" if USE_CUDA else "cpu")
print(device)

cuda


# Tensor basic
## [all tensor types](https://pytorch.org/docs/stable/tensors.html)

In [3]:
import torch

a1 = torch.Tensor([1, 2])
print(a1, a1.type())
a2 = torch.tensor([1, 2])
print(a2, a2.type())

a3 = torch.tensor([1.0, 2.0])
print(a3, a3.type())

a4 = torch.tensor([1, 2], dtype = torch.float)
print(a4, a4.type())

tensor([1., 2.]) torch.FloatTensor
tensor([1, 2]) torch.LongTensor
tensor([1., 2.]) torch.FloatTensor
tensor([1., 2.]) torch.FloatTensor


In [4]:
b1 = torch.zeros(2,3)
print(b1)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [5]:
b2 = torch.ones(2,3)
print(b2)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [6]:
# torch.manual_seed(23) # random seed
b3 = torch.rand(2, 3) # random in [0, 1)
print(b3)

tensor([[0.9687, 0.7630, 0.3282],
        [0.8687, 0.0804, 0.4477]])


In [7]:
b4 = torch.randn(3, 3) # standard normal distribution
print(b4)

tensor([[-0.4574, -1.0091, -0.7427],
        [-0.6166, -0.4068,  0.0669],
        [-1.5060,  1.3417, -0.1604]])


In [8]:
b2.zero_() # Fills self tensor with zeros
print(b2)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [9]:
c1 = torch.tensor([2])
c = c1.item() # change tensor to scalar
print(c)

2


In [10]:
d1 = torch.ones(2, 3)
d1_np = d1.numpy() # tensor to numpy
print(d1.dtype)
print(d1_np.dtype)

torch.float32
float32


In [11]:
import numpy as np
d2_np = np.array([1, 2, 3])
d2 = torch.from_numpy(d2_np)
print(d2.dtype)

torch.int32


In [12]:
d1 = torch.rand(2,3)
print(d1)
d2 = d1.tolist()
print(d2)

tensor([[0.5143, 0.6036, 0.3199],
        [0.9113, 0.5279, 0.9072]])
[[0.5143158435821533, 0.6036020517349243, 0.3198933005332947], [0.9112882614135742, 0.5279167890548706, 0.9071860313415527]]


# Shape

In [13]:
x1 = torch.tensor([[1, 2], [3, 4], [5, 6], [7, 8]])
print(x1.shape)

torch.Size([4, 2])


# index (same as numpy)

In [14]:
x1 = torch.tensor([[1, 2], [3, 4], [5, 6], [7, 8]])
print(x1[1, 1])
print(x1[1, 1].item())
print(x1[:2, 1])
print(x1[x1 < 5])

tensor(4)
4
tensor([2, 4])
tensor([1, 2, 3, 4])


In [15]:
x1 = torch.tensor([[1, 2], [3, 4], [5, 6], [7, 8]])
print(x1.T) # transpose

tensor([[1, 3, 5, 7],
        [2, 4, 6, 8]])


## Concatenates and Removes a tensor dimension

In [16]:
y1 = torch.tensor([[1, 2], [3, 4]])
y2 = torch.tensor([[5, 6], [7, 8]])

y3 = torch.cat([y1, y2], dim = 0)
print(y3, y3.shape)

y4 = torch.cat([y1, y2], dim = 1)
print(y4, y4.shape)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]) torch.Size([4, 2])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]]) torch.Size([2, 4])


In [17]:
y5 = torch.stack((y1, y2))
print(y5, y5.shape)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]]) torch.Size([2, 2, 2])


In [18]:
y6 = torch.unbind(y3)
print(y6)

(tensor([1, 2]), tensor([3, 4]), tensor([5, 6]), tensor([7, 8]))


# compare

In [19]:
v1 = torch.arange(8)
print(v1)

v2 = v1.view(2,4)
print(v2)

r = torch.max(v2, dim =1)
print(r)

tensor([0, 1, 2, 3, 4, 5, 6, 7])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
torch.return_types.max(
values=tensor([3, 7]),
indices=tensor([3, 3]))


In [20]:
r = torch.topk(v2, 2, dim = 1)
print(r)

torch.return_types.topk(
values=tensor([[3, 2],
        [7, 6]]),
indices=tensor([[3, 2],
        [3, 2]]))


In [21]:
v3 = torch.rand(2,3)
print(v3)

print(torch.argmax(v3, dim =0))
print(torch.argmax(v3, dim =1))

tensor([[0.8983, 0.6919, 0.5600],
        [0.4194, 0.7302, 0.7992]])
tensor([0, 1, 1])
tensor([0, 2])


# Tensor in CPU and GPU

In [22]:
USE_CUDA = torch.cuda.is_available()
device = torch.device("cuda" if USE_CUDA else "cpu")
print(device)

cuda


In [23]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]], device = device)
y = torch.tensor([[7, 8, 9], [0, 1, 2]], device = device)
z = x + y
print(z)

tensor([[ 8, 10, 12],
        [ 4,  6,  8]], device='cuda:0')


In [24]:
x = x.to("cpu") # change memory from gpu to cpu
y = y.to("cpu")
z = x + y
print(z)

tensor([[ 8, 10, 12],
        [ 4,  6,  8]])


In [25]:
x = x.to("cuda") # change menory from cpu to  gpu
y = y.to("cuda")
z = x + y
print(z)

tensor([[ 8, 10, 12],
        [ 4,  6,  8]], device='cuda:0')
